version: '2'
services:
  resque_web:
    build:
      context: .
    image: daocloud.io/shaobo_wu/resque_web
    environment:
      - RESQUE_WEB_HTTP_BASIC_AUTH_USER=tronclass
      - RESQUE_WEB_HTTP_BASIC_AUTH_PASSWORD=wg
      - RAILS_RESQUE_REDIS=192.168.99.1:6379
    command: passenger start --min-instance 4 --port 80
    ports:
        - "3000:80"
